---
- name: hello nodes
  hosts: webservers
  tasks:
    - name: Print Debug message
      debug:
        msg: Hello node

    - name: Update apt package index
      apt:
        update_cache: yes
...
