name: Read git commit hash and write into a file, then prepare a docker image and push it

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} #do not understand this line.
#          restore-keys: ${{ runner.os }}-maven
#
#      - name: Build with Maven
#        run: mvn clean package

      - name: Initialize with Maven
        run: mvn -N exec:exec@init

        # Get the latest Git commit hash and write to file
      - name: Write Git commit hash to file
        run: echo $(git rev-parse HEAD) > GIT_COMMIT

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t shalahur/read-commit:${GITHUB_SHA:0:6} .

        # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push shalahur/read-commit:${GITHUB_SHA:0:6}
